version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: nestjs_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjsdb
    ports:
      - "5432:5432"
    volumes:
      - /d/Train/nestJS-udemy/postgres-data:/var/lib/postgresql/data
    networks:
      - postgres_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run start:dev
    depends_on:
      - postgres
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
