version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs_app_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app # mount โค้ดจาก host
      - /usr/src/app/node_modules # แยก node_modules ออกกันทับ
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: nestjsdb
    command: npm run start:dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nest_network

  postgres:
    image: postgres:17
    container_name: nestjs_postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjsdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nest_network

networks:
  nest_network:
    driver: bridge
