# Use official Node.js LTS image
FROM node:20-alpine

# Update apk packages to reduce vulnerabilities
RUN apk update && apk upgrade --no-cache

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

RUN npm install -g @nestjs/cli

# Copy the rest of the application code
COPY . .

# Expose application port (change if needed)
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"]